-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local MsgId = {
    ReqLogin = 1000,
    RspLogin = 1001,
    ReqChat = 1002,
    RspChat = 1003,
}

return MsgId -- return the module