// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum MsgId : ushort
{
 ReqLogin = 1000,
 RspLogin = 1001,
};


}
