// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct ReqChat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x9291D76D5CC9BF89;
  public static ReqChat GetRootAsReqChat(ByteBuffer _bb) { return GetRootAsReqChat(_bb, new ReqChat()); }
  public static ReqChat GetRootAsReqChat(ByteBuffer _bb, ReqChat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReqChat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Say { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSayBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetSayBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSayArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<ReqChat> CreateReqChat(FlatBufferBuilder builder,
      StringOffset sayOffset = default(StringOffset)) {
    builder.StartObject(1);
    ReqChat.AddSay(builder, sayOffset);
    return ReqChat.EndReqChat(builder);
  }

  public static void StartReqChat(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSay(FlatBufferBuilder builder, StringOffset sayOffset) { builder.AddOffset(0, sayOffset.Value, 0); }
  public static Offset<ReqChat> EndReqChat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReqChat>(o);
  }
};


}
